### ISSUE TITLE
Validator.js 2.0

### ISSUE THREAD

**Issue by garygreen** [mikeerickson/validatorjs#46]
I think it would be a good idea to move towards a goal of version 2.0. I know there's a big thing about backwards compatibility, but it's pretty stable at the moment so let's work towards a major release knowing we can change a few things without being overly concerned with backwards compatibility etc. In any case, the upgrade path will be very straight forward.

So for version 2.0:
- [x] Asynchronous validation #37 
- [x] Improve restructuring of library by using browserify issue #45 
- [x] Run tests on node and browser, switch to mocha
- [x] Ability to override default messages issue #41 
- [x] Improve language support by not requiring custom validator builds and easy switching of language PR #42 
- [x] Change to not validating as soon as instantiated issue #44 
- [x] Array validation rule
- [x] Fixed to allow unsigned values on integer rule
- [x] Ability to format attributes issue #54 
- [x] Add 'required_*' conditional rules issue #57 
- [x] Docblock entire codebase
- [x] Readme
- [x] Change log / Upgrade guide

**Comment by iamdtang** [comment]
Hey Gary,

I think it would be good to move to a 2.0 release. I think that for backwards compatible changes, we can add those to the 1.x release and then for breaking changes, add that to 2.0. This way if anyone is using 1.x and wants to migrate to 2.0 it shouldn't be as many changes as opposed to if we do everything just for 2.0.

**Comment by garygreen** [comment]
Hi David

I don't think there will be many major breaking changes, but as a whole there will be a number of fixes/features/minor breaks etc so it might just be easier and make more sense to release everything under a major version and document in changelog anything that needs updating in their app -- upgrade path will be super simple in any case.

**Comment by iamdtang** [comment]
Ok, let's make it another major release

**Comment by garygreen** [comment]
@skaterdav85 I think we're nearing release of 2.0. Still a few things left to do but overall I think it's pretty stable. I'll be tidying up some bits before release (and update readme and add changelog) but what do you think overall so far?

**Comment by iamdtang** [comment]
I like what you've done! I agree we can release 2.0 soon. Thanks for all the hard work and taking the lead on this since I have been pretty busy lately.

**Comment by garygreen** [comment]
@skaterdav85 I've added a changelog and updated readme for 2.0.0. I think it's looking pretty good for release soon. Would you be able to review the changes in master and let me know if your happy with a new release? :smile: 

https://github.com/skaterdav85/validatorjs/blob/1a613ad941867593e6f2ff4fade63a2d9a14bae4/CHANGELOG.md

**Comment by iamdtang** [comment]
everything looks good to me! nice work!

**Comment by garygreen** [comment]
Ok cool! Would you like me to release 2.0 or shall I leave it to you?

**Comment by iamdtang** [comment]
leave it to you =). ive been swamped with other stuff so haven't really had
time to dedicate to this. awesome work you've done!

On Fri, Jul 24, 2015 at 3:13 AM, Gary Green notifications@github.com
wrote:

> Ok cool! Would you like me to release 2.0 or shall I leave it to you?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/skaterdav85/validatorjs/issues/46#issuecomment-124462885
> .

## 

David

**Comment by iamdtang** [comment]
Hey @garygreen, still planning on releasing 2.0?

**Comment by garygreen** [comment]
Yes, sorry its taken so long. I've been so busy with work and personal
stuff. Will try and cut a release over next few days.

**Comment by garygreen** [comment]
@skaterdav85 would you mind adding me as a collaborator on npm? Will make it easier when I go to publish :smile:

**Comment by iamdtang** [comment]
done!

On Sun, Sep 6, 2015 at 9:27 AM, Gary Green notifications@github.com wrote:

> @skaterdav85 https://github.com/skaterdav85 would you mind adding me as
> a collaborator on npm? Will make it easier when I go to publish [image:
> :smile:]
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/skaterdav85/validatorjs/issues/46#issuecomment-138097769
> .

## 

David

**Comment by garygreen** [comment]
@skaterdav85 I've just released 2.0.0. Enjoy ! :smile:

**Comment by iamdtang** [comment]
awesome work! Thanks Gary!

On Sat, Sep 19, 2015 at 6:49 AM, Gary Green notifications@github.com
wrote:

> @skaterdav85 https://github.com/skaterdav85 I've just released 2.0.0.
> Enjoy ! [image: :smile:]
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/skaterdav85/validatorjs/issues/46#issuecomment-141669911
> .

## 

David
